import { transform } from "framer-motion";
const theme = {
  breakpoints: ["1024px"],
  fonts: {
    body: '"Dandi Grotesk", sans-serif',
    display: '"Dandi Grotesk Display", sans-serif',
    medium: '"Dandi Grotesk Medium", sans-serif',
  },
  fontWeights: {
    normal: 500,
    bold: 500,
  },
  fontSizes: {
    heading1: ["36px", "60px"],
    heading2: ["32px", "40px"],
    heading3: ["28px", "28px"],
    heading4: ["18px", "18px"],
    body: ["16px", "20px"],
    small: ["13px", "13px"],
    nav: ["14px", "14px"],
  },
  lineHeights: {
    heading1: ["43.2px", "64px"],
    heading2: ["38.4px", "48px"],
    heading3: ["32px", "32px"],
    heading4: ["26px", "26px"],
    body: ["24px", "32px"],
    small: ["15.34px", "15.34px"],
  },
  colors: {
    black: "#1A1A1D",
    grey: "#909095",
    white: "#f2f2f2",
    lightGray: "#F8F8F8",
    clearWhite: "#FFFFFF",
    orange: "#FF9133",
    yellow: "#FFD93B",
    lightYellow: "#FBF792",
    darkTurquoise: "#1A1A1D",
    turquoise: "#A4F0F4",
    lightTurquoise: "#DFFFFF",
    darkBlue: "#0227C5",
    blue: "#335AFF",
    lightBlue: "#C6D9FF",
    darkViolet: "#A837F8",
    violet: "#F9D2FF",
    lightViolet: "#FDF1FF",
  },
  colWidthMob: `calc(calc(100vw - 140px)/6)`,
  colWidthDesktop: `calc(calc(100vw - 520px)/12)`,
  grid: {
    display: "grid",
    gridTemplateColumns: ["repeat(6,1fr)"],
    gridTemplateRows: "auto",
    gridGap: ["20px", "40px"],
    mx: ["20px", "40px"],
  },
  wrapper: {},
  pages: {
    home: {
      top: {
        // height: ["542px", "677px"],

        mx: ["20px", "40px"],
        bg: "transparent",
        bigLogo: {
          svg: {
            position: "fixed",
            zIndex: 9999,
            top: ["24px", "44px"],
            left: ["20px", "40px"],
            height: [(t) => t.colWidthMob, (t) => t.colWidthDesktop],
            width: ["125px", "367px"],
            mb: ["20px", "40px"],
            transform: "rotate(90deg) translateX(-30%)",
            transformOrigin: "bottom left",
          },
        },
        header: {
          display: "grid",
          gridTemplateColumns: ["repeat(6, 1fr)", "repeat(12,1fr)"],
          columnGap: ["20px", "40px"],
          gridTemplateRows: "auto",
          h1: {
            gridArea: ["1/2/2/-1", "1/7/2/-1"],
            ml: [(t) => `calc(${t.colWidthMob} + 10px)`],
            mt: [`124px`],
          },
          button: {
            gridArea: ["2/2/3/6", "2/7/3/-1"],
            ml: [(t) => `calc(${t.colWidthMob} + 10px)`],
            height: "48px",
            // ml: [0, "5.4vw"],
            mt: ["24px", "48px"],
            bg: "yellow",

            borderRadius: "200px",
            display: "flex",
            flexFlow: "row",
            justifyContent: "center",
            alignItems: "center",
            a: {
              textDecoration: "none",
              color: "black",
            },
            p: {
              fontSize: "16px",
            },
          },
        },
        bars: {
          position: "absolute",
          left: 0,
          top: 325,
          pt: "16px",
          width: "100%",
          height: "191px",
          // height: "250px",
          ".barWrapper": {
            position: "relative",
            width: "100%",
            height: "100%",
          },
          "#bar1": {
            bg: "turquoise",
            width: [(t) => `calc(${t.colWidthMob} + 10px)`],
            height: "250px",
            borderRadius: "7px",
            ml: ["20px"],
            position: "absolute",
            backgroundRepeat: "no-repeat",
            backgroundImage: (t) =>
              `linear-gradient(to right, ${t.colors.blue},${t.colors.blue})`,
            backgroundPosition: "0 175px",
            backgroundSize: "100% 75px",
          },
          "#bar2": {
            bg: "turquoise",
            width: [(t) => `calc(${t.colWidthMob} + 10px)`],
            height: "153px",
            top: "97px",
            borderRadius: "7px",
            ml: [(t) => `calc(calc(${t.colWidthMob} * 2) + 40px)`],
            position: "absolute",
            backgroundRepeat: "no-repeat",
            backgroundImage: (t) =>
              `linear-gradient(to right, ${t.colors.blue},${t.colors.blue})`,
            backgroundPosition: "0 78px",
            backgroundSize: "100% 75px",
          },
          "#bar3": {
            bg: "turquoise",
            width: [(t) => `calc(${t.colWidthMob} + 10px)`],
            height: "75px",
            top: "175px",
            borderRadius: "0px 0px 7px 7px",
            ml: [(t) => `calc(calc(${t.colWidthMob} * 3.5) + 80px)`],
            position: "absolute",
            backgroundRepeat: "no-repeat",
            backgroundImage: (t) =>
              `linear-gradient(to right, ${t.colors.blue},${t.colors.blue})`,
            backgroundPosition: "0 0",
            backgroundSize: "100% 75px",
          },
        },
        ".spacer": {
          height: "191px",
        },
      },
      learnmore: {
        bg: "violet",

        ".learnMoreText": {
          gridArea: ["1/2/2/-1"],
          ml: [(t) => `calc(${t.colWidthMob} + 10px)`],
          pt: "101px",
          color: "black",
          fontFamily: "display",
          fontWeight: "500",
          display: "flex",
          alignItems: "flex-start",
          justifyContent: "flex-end",
          svg: {
            ml: "10px",
            pt: "15px",
          },
        },
        ".laptopImage": {
          gridArea: ["2/1/3/-1"],
          height: "250px",
          position: "relative",
          ".imageWrapper": {
            position: "absolute",
            top: 0,
            bottom: 0,
            left: "-20px",
            width: "100vw",
            bg: "grey",
          },
        },
        ".learnMoreHeader": {
          gridArea: ["3/1/4/-1"],
          color: "black",
        },
        ".learnMoreMainText": {
          gridArea: ["4/1/5/-1"],
          color: "black",
          mb: ["168px"],
        },
      },
      carousel: {
        bg: "transparent",
        ".carouselHeader": {
          gridArea: ["1/1/2/-1"],
          mt: ["80px"],
          h2: {
            fontFamily: "display",
            fontWeight: "500",
            mb: "20px",
          },
          p: {
            fontFamily: "body",
            fontWeight: "400",
            mb: "24px",
          },
        },
        ".carouselSpacer": {
          gridArea: ["2/1/3/-1"],
          height: "200px",
          position: "relative",
          div: {
            position: "absolute",
            bg: "#1F1F21",
            left: "-20px",
            height: "100%",
            width: "100vw",
          },
        },
        ".carouselMain": {
          mt: ["30px"],
          gridArea: ["3/1/4/-1"],
          width: "100%",
          display: "flex",
          flexFlow: "column wrap",

          ".carouselItem": {
            mb: ["24px"],
            ".carouselItemHeader": {
              position: "relative",
              display: "flex",
              alignItems: "center",
              ".progressBar": {
                position: "absolute",
                height: "32px",
                width: "2px",
                bg: "#EDEDF1",
                borderRadius: "6px",
                ".progressBarAnimation": {
                  bg: "turquoise",
                  width: "100%",
                  borderRadius: "6px",
                },
              },
              p: {
                ml: "20px",
                fontWeight: "500",
                fontFamily: "medium",
              },
            },
            ".carouselItemBody": {
              mx: "20px",
              mt: "8px",
              p: {
                fontWeight: "400",
                fontFamily: "body",
              },
            },
          },
        },
      },
      payequity: {
        bg: "lightGray",
        ".payEquityHeader": {
          gridArea: ["1/1/2/-1"],
          mt: ["80px"],
          color: "black",
          h2: {
            fontFamily: "display",
            fontWeight: "500",
            fontSize: "32px",
            lineHeight: "38.4px",
          },
          ".payEquityBody": {
            mt: "20px",
            fontWeight: "400",
            lineHeight: "24px",
            fontFamily: "body",
          },
        },
        ".payEquityGraphic": {
          position: "relative",
          gridArea: ["2/1/3/-1"],
          height: "600px",
          div: {
            position: "absolute",
            bg: "#F2F2F2",
            height: "100%",
            width: "100vw",
            left: "-20px",
          },
        },
      },
      partners: {
        bg: "clearWhite",
        ".partnersHeader": {
          color: "black",
          mt: "80px",
          gridArea: ["1/1/2/-1"],
          h2: {
            fontSize: "32px",
            fontFamily: "display",
            fontWeight: "500",
            lineHeight: "38.4px",
          },
        },
        ".logoCarousel": {
          gridArea: ["2/1/3/-1"],
          height: "250px",
          position: "relative",
          div: {
            position: "absolute",
            height: "100%",
            width: "100vw",
            left: "-20px",
            bg: "black",
          },
        },
      },
      advancedei: {
        bg: "lightTurquoise",
        ".advancedeiHeader": {
          gridArea: ["1/1/2/-1"],
          h2: {
            mt: "80px",
            fontFamily: "display",
            fontWeight: "500",
            color: "black",
          },
          ".advancedeiSub": {
            mt: "30px",
            fontFamily: "body",
            fontWeight: "400",
            color: "black",
          },
          ".advancedeiLink": {
            mt: "8px",
            mb: "20px",
            p: {
              fontFamily: "medium",
              fontWeight: "500",
            },
          },
        },
        ".advancedeiGraphics": {
          gridArea: ["2/1/3/-1"],
          height: "120px",
          position: "relative",
          width: "100vw",
          left: ["-20px", "40px"],
          ".advancedeiBox1": {
            position: "absolute",
            left: 0,
            bottom: 0,
            height: "67px",
            width: "115px",
            bg: "#02C3CF",
            zIndex: 99,
          },
          ".advancedeiBox2": {
            position: "absolute",
            left: "42px",
            bottom: "0",
            width: "134px",
            height: "120px",
            bg: "#A4F0F4",
            zIndex: 89,
          },
        },
      },
      marketplacepartners: {
        bg: "lightViolet",
        height: "630px",
      },
    },
  },
  components: {
    navigation: {
      position: "fixed",
      height: "94px",
      width: "100%",
      bg: "black",
      display: ["none", "flex"],
      fontFamily: "body",

      justifyContent: "flex-end",
      px: ["40px"],
      pt: ["44px"],
      ".item": {
        fontSize: "nav",
        lineHeight: "small",
        color: "white",
        ml: ["32px"],
        textDecoration: "none",
      },
      ".login": {
        color: "yellow",
        display: "flex",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        ".arrow": {
          pl: "14px",
        },
      },
    },
    mobilenav: {
      position: "fixed",
      zIndex: 1000,
      display: ["flex", "none"],
      justifyContent: "space-between",
      height: "74px",
      width: "100%",
      bg: "black",
      ".hamburger": {
        mr: "20px",
        mt: "33px",
        position: "relative",
        height: "21px",
        width: "25px",
        span: {
          position: "absolute",
          left: 0,
          p: 0,
          m: 0,
          height: "3px",
          width: "25px",
          bg: "white",
        },
      },
      ".logo": {
        mt: "24px",
        ml: "20px",
        svg: {
          path: {
            fill: "white",
          },
        },
      },
    },
    footer: {
      bg: "#1F1F21",
      ".footerHeader": {
        gridArea: ["1/1/2/-1"],
        h2: {
          mt: ["80px"],
          fontFamily: "display",
          fontWeight: "500",
          fontSize: "28px",
        },
        p: {
          mt: ["20px"],
          mb: ["20px"],
          fontFamily: "body",
          fontWeight: "400",
        },
      },
      ".footerForm": {
        gridArea: ["2/1/3/-1"],
        display: "flex",
        flexFlow: "column wrap",
      },
      ".socials": {
        gridArea: ["3/1/4/-1"],
        mt: ["20px"],
        display: "grid",
        gridTemplateColumns: ["repeat(6,1fr)"],
        columnGap: ["20px"],
        gridTemplateRows: "auto",
      },
      ".signupLink": {
        gridArea: ["4/1/5/-1"],
        mb: ["44px"],
      },
      ".bottomSection": {
        gridArea: ["5/1/6/-1"],
        p: {
          mt: ["12px"],
          mb: ["40px"],
          fontSize: ["13px"],
          fontFamily: "body",
          fontWeight: "500",
          color: "white",
          opacity: 0.24,
        },
      },
    },
    learnMoreLink: {
      textDecoration: "none",
      display: "flex",

      alignItems: "center",
      p: {
        mr: "10px",
      },
    },
  },
  forms: {
    input: {
      height: ["64px"],
      bg: "#262629",
      px: ["24px"],
      mb: ["12px"],
      borderRadius: "8px",
      border: "none",
      fontFamily: "body",
      fontWeight: "400",
      fontSize: ["18px"],
      color: "white",
      ":focus": {
        outline: "none",
      },
      "::placeholder": {
        opacity: 0.24,
      },
    },
    select: {
      // A reset of styles, including removing the default dropdown arrow
      appearance: "none",
      // Additional resets for further consistency
      border: "none",
      borderRadius: "8px",
      // p: " 0 1em 0 0",
      mb: ["12px"],
      px: ["24px"],
      width: "100%",
      height: ["64px"],
      fontFamily: "body",
      fontSize: ["18px"],
      cursor: "pointer",
      lineHeight: "inherit",
      outline: "none",
      bg: "#262629",
      color: "white",
      option: {},
    },
  },
  buttons: {
    primary: {
      bg: "#3A3A3D",
      height: ["56px"],
      mt: ["12px"],
      color: "black",
      borderRadius: "200px",
      width: ["191px"],
      fontFamily: "body",
      fontWeight: "500",
      fontSize: ["18px"],
      cursor: "pointer",
    },
  },
  styles: {
    root: {
      bg: "black",
      color: "white",
    },
    h1: {
      fontFamily: "display",
      fontSize: ["36px", "60px"],
      lineHeight: ["43.2px", "64px"],
      fontWeight: "500",
      m: 0,
    },
    h2: {
      fontFamily: "body",
      fontSize: ["32px", "40px"],
      lineHeight: ["38.4px"],
      fontWeight: "bold",
      m: 0,
    },
    h3: {
      fontFamily: "body",
      fontSize: "heading3",
      lineHeight: "heading3",
      fontWeight: "bold",
      m: 0,
    },
    h4: {
      fontFamily: "body",
      fontSize: "heading4",
      lineHeight: "heading4",
      fontWeight: "normal",
      m: 0,
    },
    p: {
      fontFamily: "body",
      fontSize: ["16px", "20px"],
      lineHeight: "body",
      fontWeight: "400",
      m: 0,
    },
    h5: {
      fontFamily: "body",
      fontSize: "small",
      lineHeight: "small",
      fontWeight: "normal",
      m: 0,
    },
  },
};

export default theme;
